FROM node:lts-alpine3.23 AS builder

# build the app

WORKDIR /app

COPY backend/package*.json ./backend/
RUN npm --prefix ./backend install

COPY frontend/package*.json ./frontend/
RUN npm --prefix ./frontend install

COPY backend/ ./backend/
COPY frontend/ ./frontend/

RUN npm --prefix ./backend run build:prod

# deploy prod image
FROM node:lts-alpine3.23 AS runner

WORKDIR /app

COPY --from=builder /app/backend/package*.json ./
RUN npm install --omit=dev

ENV DEPLOYMENT='aws'
ENV AWS_KAFKA_CONNECT_URL='kafka-connect.lattice.local:9092'
ENV AWS_KAFKA_BROKERS='kafka-1:19092,kafka-2:19092,kafka-3:19092'
ENV AWS_SCHEMA_REGISTRY_URL='apicurio.lattice.local:9092'
ENV AWS_APICURIO_REGISTRY_URL='apicurio.lattice.local:9092/apis/registry/v2'

ENV DEPLOYMENT='aws'
ENV PORT='5000'


COPY --from=builder /app/backend/dist ./dist

EXPOSE 5000
CMD ["node", "./dist/app.js"]



